### ISSUE TITLE
Issues with react-with-styles in electron

### ISSUE THREAD

**Issue by jwaldrip** [airbnb/react-with-styles#80]
Uncaught TypeError: makeFromTheme is not a function
    at /Users/jwaldrip/dev/src/github.com/CommercialTribe/companion/node_modules/react-with-styles/lib/ThemedStyleSheet.js:63:40
    at Array.forEach (native)
    at Object.create (/Users/jwaldrip/dev/src/github.com/CommercialTribe/companion/node_modules/react-with-styles/lib/ThemedStyleSheet.js:58:23)
    at withStyles (/Users/jwaldrip/dev/src/github.com/CommercialTribe/companion/node_modules/react-with-styles/lib/withStyles.js:79:59)
    at Object.<anonymous> (/Users/jwaldrip/dev/src/github.com/CommercialTribe/companion/src/react/full-logo/full-logo.component.jsx:30:47)
    at Object.<anonymous> (/Users/jwaldrip/dev/src/github.com/CommercialTribe/companion/src/react/full-logo/full-logo.component.jsx:74:3)
    at Module._compile (module.js:571:32)
    at Object.require.extensions.(anonymous function) [as .jsx] (/Users/jwaldrip/dev/src/github.com/CommercialTribe/companion/node_modules/electron-compile/lib/require-hook.js:77:14)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by ljharb** [comment]
Can you share your "full-logo.component" file?
